//
//  PokemonsPresenter.swift
//  VIPPokemon
//
//  Created by Marlon David Ruiz Arroyave on 9/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonsPresentationLogic {
    func presentFetchedPokemons(response: Pokemons.FetchPokemons.Response)
}

class PokemonsPresenter: PokemonsPresentationLogic {
    weak var viewController: PokemonsDisplayLogic?

    func presentFetchedPokemons(response: Pokemons.FetchPokemons.Response) {
        switch response.result {
        case .success(let pokemons):
            let displayedPokemons = pokemons.map { Pokemons.FetchPokemons.ViewModel.DisplayedPokemon(id: $0.id, name: $0.name, image: $0.image, types: $0.types) }
            let viewModel = Pokemons.FetchPokemons.ViewModel(result: .success(displayedPokemons))
            viewController?.displayFetchedPokemons(viewModel: viewModel)

        case .failure(let error):
            let viewModel = Pokemons.FetchPokemons.ViewModel(result: .failure(error))
            viewController?.displayFetchedPokemons(viewModel: viewModel)
        }
    }
}
