//
//  PokemonsRouter.swift
//  VIPPokemon
//
//  Created by Marlon David Ruiz Arroyave on 9/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PokemonsRoutingLogic {
    func routeToDetailPokemon(segue: UIStoryboardSegue?)
}

protocol PokemonsDataPassing {
    var dataStore: PokemonsDataStore? { get }
}

class PokemonsRouter: NSObject, PokemonsRoutingLogic, PokemonsDataPassing {
    weak var viewController: PokemonsViewController?
    var dataStore: PokemonsDataStore?

    // MARK: Routing

    func routeToDetailPokemon(segue: UIStoryboardSegue?) {
        if let segue = segue {
            guard
                let destinationVC = segue.destination as? DetailPokemonViewController,
                var destinationDS = destinationVC.router?.dataStore
            else {
                return
            }

            passDataToDetailPokemon(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            guard
                let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailPokemonViewController") as? DetailPokemonViewController,
                var destinationDS = destinationVC.router?.dataStore
            else {
                return
            }
            passDataToDetailPokemon(source: dataStore!, destination: &destinationDS)
            navigateToDetailPokemon(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation

    func navigateToDetailPokemon(source: PokemonsViewController, destination: DetailPokemonViewController) {
        source.present(destination, animated: true)
    }

    // MARK: Passing data

    func passDataToDetailPokemon(source: PokemonsDataStore, destination: inout DetailPokemonDataStore) {
        guard
            let viewController = viewController,
            let indexPaths: [IndexPath] = viewController.collectionView.indexPathsForSelectedItems
        else {
            return
        }
        let selectedRow = indexPaths[0].row
        destination.pokemon = source.pokemons?[selectedRow]
    }
}
