//
//  DetailPokemonRouter.swift
//  VIPPokemon
//
//  Created by Marlon David Ruiz Arroyave on 10/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailPokemonRoutingLogic {
  // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DetailPokemonDataPassing {
  var dataStore: DetailPokemonDataStore! { get }
}

class DetailPokemonRouter: NSObject, DetailPokemonRoutingLogic, DetailPokemonDataPassing {
  weak var viewController: DetailPokemonViewController?
  var dataStore: DetailPokemonDataStore!
  
  // MARK: Routing
  
  // func routeToSomewhere(segue: UIStoryboardSegue?)
  // {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  // }

  // MARK: Navigation
  
  // func navigateToSomewhere(source: DetailPokemonViewController, destination: SomewhereViewController)
  // {
  //  source.show(destination, sender: nil)
  // }
  
  // MARK: Passing data
  
  // func passDataToSomewhere(source: DetailPokemonDataStore, destination: inout SomewhereDataStore)
  // {
  //  destination.name = source.name
  // }
}
