//
//  DetailPokemonPresenter.swift
//  VIPPokemon
//
//  Created by Marlon David Ruiz Arroyave on 10/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPokemonPresentationLogic {
    func presentPokemon(response: DetailPokemon.GetPokemon.Response)
}

class DetailPokemonPresenter: DetailPokemonPresentationLogic {
    weak var viewController: DetailPokemonDisplayLogic?
    
    // MARK: Do something
    
    func presentPokemon(response: DetailPokemon.GetPokemon.Response) {
        let pokemon = response.pokemon
        let displayedPokemon = DetailPokemon
            .GetPokemon
            .ViewModel
            .DisplayedPokemon(id: pokemon.id,
                              name: pokemon.name,
                              image: pokemon.image,
                              types: pokemon.types,
                              weight: pokemon.weight,
                              baseExperience: pokemon.baseExperience,
                              abilities: pokemon.abilities)
        let viewModel = DetailPokemon.GetPokemon.ViewModel(displayedPokemon: displayedPokemon)
        viewController?.displayPokemon(viewModel: viewModel)
    }
}
