//
//  DetailPokemonInteractor.swift
//  VIPPokemon
//
//  Created by Marlon David Ruiz Arroyave on 10/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPokemonBusinessLogic {
    func getPokemon(request: DetailPokemon.GetPokemon.Request)
}

protocol DetailPokemonDataStore {
    var pokemon: Pokemon? { get set }
}

class DetailPokemonInteractor: DetailPokemonBusinessLogic, DetailPokemonDataStore {
    var presenter: DetailPokemonPresentationLogic?
    var pokemon: Pokemon?

    func getPokemon(request: DetailPokemon.GetPokemon.Request) {
        guard let pokemon = pokemon else {
            return
        }

        let response = DetailPokemon.GetPokemon.Response(pokemon: pokemon)
        presenter?.presentPokemon(response: response)
    }
}
