//
//  DetailPokemonViewController.swift
//  VIPPokemon
//
//  Created by Marlon David Ruiz Arroyave on 10/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPokemonDisplayLogic: AnyObject {
    func displayPokemon(viewModel: DetailPokemon.GetPokemon.ViewModel)
}

class DetailPokemonViewController: UIViewController {

    // MARK: - Properties

    var interactor: DetailPokemonBusinessLogic?
    var router: (NSObjectProtocol & DetailPokemonRoutingLogic & DetailPokemonDataPassing)?

    private let margin: CGFloat = 20

    private var gradient: CAGradientLayer? {
        guard let pokemon = pokemon else { return nil }
        let gradient = PokemonColor.typeLinearGradient(name: pokemon.primaryType())
        gradient.frame = view.bounds
        return gradient
    }

    var pokemon: DetailPokemon.GetPokemon.ViewModel.DisplayedPokemon?

    lazy private var closeButon: UIButton = {
        let button = UIButton(type: .close)
        button.addTarget(self, action: #selector(closeButton), for: .touchUpInside)
        button.translatesAutoresizingMaskIntoConstraints = false
        return button
    }()

    lazy private var nameLabel: UILabel = {
        let label = UILabel()
        label.textAlignment = .right
        label.font = UIFont.boldSystemFont(ofSize: 30)
        label.textColor = .white
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()

    lazy private var idLabel: UILabel = {
        let label = UILabel()
        label.textAlignment = .right
        label.font = UIFont.boldSystemFont(ofSize: 23)
        label.textColor = .white
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()

    lazy private var typesStackView: UIStackView = {
        let stackView = UIStackView()
        stackView.axis = .horizontal
        stackView.distribution = .fill
        stackView.spacing = margin/2
        stackView.translatesAutoresizingMaskIntoConstraints = false
        return stackView
    }()

    lazy private var imageView: UIImageView = {
        let view = UIImageView()
        view.translatesAutoresizingMaskIntoConstraints = false
        view.contentMode = .scaleAspectFit
        return view
    }()

    lazy private var cardView: CardView = {
        let title = "About"
        let cardView = CardView(card: Card(title: title, items: items))
        cardView.translatesAutoresizingMaskIntoConstraints = false
        return cardView
    }()

    lazy private var items: [Item] = {
        var items = [Item]()

        guard let pokemon = pokemon else { return items }

        // abilities
        if let abilities = pokemon.abilities {
            let title = "Abilities"
            let description = abilities.joined(separator: "\n")
            let item = Item(title: title, description: description)
            items.append(item)
        }

        // weight
        let weight = "Weight"
        items.append(Item(title: weight, description: "\(pokemon.weight/10) kg"))

        // baseExperience
        let baseExperience = "Base Experience"
        items.append(Item(title: baseExperience, description: "\(pokemon.baseExperience)"))

        return items
    }()

    @objc private func closeButton(sender: UIButton) {
        dismiss(animated: true, completion: nil)
    }

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        DetailPokemonConfigurator.configureModule(viewController: self)
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        getPokemon()
        setupUI()
    }

    // MARK: Public Methods

    func getPokemon() {
        let request = DetailPokemon.GetPokemon.Request()
        interactor?.getPokemon(request: request)
    }

    // MARK: Private Methods

    private func setupUI() {
        view.addSubview(closeButon)
        closeButon.topAnchor.constraint(equalTo: view.topAnchor, constant: margin).isActive = true
        closeButon.leftAnchor.constraint(equalTo: view.leftAnchor, constant: margin).isActive = true

        view.addSubview(nameLabel)
        nameLabel.topAnchor.constraint(equalTo: closeButon.bottomAnchor, constant: margin).isActive = true
        nameLabel.leftAnchor.constraint(equalTo: closeButon.leftAnchor).isActive = true
        nameLabel.widthAnchor.constraint(lessThanOrEqualTo: view.widthAnchor, multiplier: 0.7).isActive = true

        view.addSubview(idLabel)
        idLabel.topAnchor.constraint(equalTo: nameLabel.bottomAnchor).isActive = true
        idLabel.rightAnchor.constraint(equalTo: view.rightAnchor, constant: -margin).isActive = true

        view.addSubview(typesStackView)
        typesStackView.topAnchor.constraint(equalTo: nameLabel.bottomAnchor, constant: margin).isActive = true
        typesStackView.leftAnchor.constraint(equalTo: closeButon.leftAnchor).isActive = true
        typesStackView.widthAnchor.constraint(lessThanOrEqualTo: view.widthAnchor, multiplier: 0.7).isActive = true

        view.addSubview(cardView)
        cardView.topAnchor.constraint(equalTo: view.topAnchor, constant: view.frame.size.height/2.5).isActive = true
        cardView.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
        cardView.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true
        cardView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true

        view.addSubview(imageView)
        imageView.bottomAnchor.constraint(equalTo: cardView.topAnchor, constant: margin * 2).isActive = true
        imageView.centerXAnchor.constraint(equalTo: cardView.centerXAnchor).isActive = true
        imageView.heightAnchor.constraint(equalToConstant: 200).isActive = true
        imageView.widthAnchor.constraint(equalToConstant: 200).isActive = true
    }

}

// MARK: - DetailPokemonDisplayLogic

extension DetailPokemonViewController: DetailPokemonDisplayLogic {

    func displayPokemon(viewModel: DetailPokemon.GetPokemon.ViewModel) {
        pokemon = viewModel.displayedPokemon
        guard let pokemon = pokemon else { return }
        nameLabel.text = pokemon.name.capitalized
        idLabel.text = pokemon.formattedNumber()

        guard let gradient = gradient else { return }
        view.layer.insertSublayer(gradient, at: 0)

        if let image = pokemon.image, let url = URL(string: image) {
            imageView.kf.setImage(with: url)
        }

        guard let types = pokemon.types else { return }
        buildTypes(types)
    }

    private func buildTypes(_ types: [String]) {
        types.forEach { type in
            let padding = 20.0
            let label = UILabel()
            label.textAlignment = .center
            label.font = UIFont.boldSystemFont(ofSize: 17)
            label.textColor = .white
            label.translatesAutoresizingMaskIntoConstraints = false
            label.text = type.capitalized
            label.backgroundColor = .white.withAlphaComponent(0.30)
            label.layer.cornerRadius = 7.0
            label.layer.masksToBounds = true
            let paddedWidth = label.intrinsicContentSize.width + padding
            label.widthAnchor.constraint(equalToConstant: paddedWidth).isActive = true
            typesStackView.addArrangedSubview(label)
        }
    }

}
